### ISSUE TITLE
FILTER JOIN GROUBY

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#11]
I propose to embed FILTER within a JOIN.
- multi-criteria support
- same `@ref` and `@value` as for ATTRIBUTE

```xml
    <GLOBALS>
      <INSTANCE ID="_TimeSeries" dmtype="cube:SparseCube">
        <ATTRIBUTE dmrole="cube:SparseCube.data">
          <COLLECTION>
            <JOIN tableref="Results" dmref="_cube1_data">
                <FILTER>
                    <COL ref="col1" value="12"/>
                    <COL ref="col2" value="GFilter"/>
                <FILTER>
            </JOIN>
          </COLLECTION>
        </ATTRIBUTE>
      </INSTANCE>
    </GLOBALS>
    <TEMPLATES tableref="Results">
      <INSTANCE dmtype="cube:NDPoint" ID="_cube1_data">
	...
      </INSTANCE>
    </TEMPLATES>
```

**Comment by mcdittmar** [comment]
I'll want to see how this element may have changed spec from the 'merged' syntax proposal.
I'd like to keep the content of FILTER in line with the content of JOIN/GROUP_BY in that these are KEY operations.. so would like to use KEY content.

Is this only expected to be used in this context (within JOIN)?  
The idea being that this singleton INSTANCE is contains only specific records from the referenced table.

**Comment by lmichel** [comment]
I'd in mind that the purpose was not the same, 
Anyway, I'm OK with KEY.

The filter is used when iterating on table rows, this is why it is enclosed in JOIN.
You could imagine to use it on collections of static elements, but I do not see any concrete usage that cannot be solved with static refs.

Anyway, FILTER is complex element that can be reused in other places if needed.
I propose to start with defining FILTER as a potential JOIN child.

**Comment by lmichel** [comment]
Can we consolidate FILTER?

**Comment by mcdittmar** [comment]
> Can we consolidate FILTER?

I'm not sure what you mean by 'consolidate' here.
I've been busy with other things the past couple days.. am looking at this proposal now.

**Comment by lmichel** [comment]
I mean: _take it as it is here_

**Comment by mcdittmar** [comment]
Here are my thoughts as I went through the review..  I think you'll like the conclusion.

I'm trying to keep things consistent with respect to the KEY concept in these tags.

For #6 we migrated the singular KEY tag (of the merged syntax) to the respective PRIMARYKEY/FOREIGNKEY pairs to accommodate the cases.

Above, what you show as "COL" contains both, which is in line with the original KEY specification.
  * the foreign key, as column in the target TABLE
  * the primary key, as a hard-coded value

I think we can make things work with the KEY node which allows one to specify:  
a) just the primary key, b) just the foreign key, or c) both  
But this gets pretty hard to describe

So, I'm thinking it might be best and easiest to describe FILTER _as a key_, rather than containing keys.
Your example above becoming:
```xml
    <GLOBALS>
      <INSTANCE ID="_TimeSeries" dmtype="cube:SparseCube">
        <ATTRIBUTE dmrole="cube:SparseCube.data">
          <COLLECTION>
            <JOIN tableref="Results" dmref="_cube1_data">
                <FILTER ref="col1" value="12"/>
                <FILTER ref="col2" value="GFilter"/>
            </JOIN>
          </COLLECTION>
        </ATTRIBUTE>
      </INSTANCE>
    </GLOBALS>
    <TEMPLATES tableref="Results">
      <INSTANCE dmtype="cube:NDPoint" ID="_cube1_data">
	...
      </INSTANCE>
    </TEMPLATES>
```

* ref == foreign key (column in target table)
* value == primary key ( hard-coded value )

NOTE: this matches the MIVOT FILTER spec.!!
NOTE: this does not allow for using a PARAM/FIELD as a filter 'value'..  
IF we want/need to do that, I'd suggest making the element signature match the original KEY spec.  allowing the primary key to be either a reference or hard-coded value.
```xml
<FILTER foreignkey={ref} primarykey={ref} value={value} />
```

**Comment by lmichel** [comment]
You are right, I like it!
Stacking filters is more easy to understand than stacking keys within a FILTER, and one nesting level less for the same price

I propose to keep this solution and to work out GROUPBY for which the main concern remains source ID extraction   (the value of the key used for grouping)

Once this will be OK, we will have to discuss the dmrole_in_instance issue and then most of the job will be done, isn't it?
