### ISSUE TITLE
GROUP_BY key extraction issue

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#3]
Let's consider the following data table
```xml
<FIELD ID="_source_name"/>
<FIELD ID="_time"/>
<FIELD ID="_mag"/>
<TR><TD>source1></TD><TD>Time11></TD><TD>Mag11></TD></TR>
<TR><TD>source1></TD><TD>Time12></TD><TD>Mag12></TD></TR>
<TR><TD>source2></TD><TD>Time21></TD><TD>Mag21></TD></TR>
<TR><TD>source2></TD><TD>Time22></TD><TD>Mag22></TD></TR>
```
To be mapped on a model associating photometric points to a source name. `source:[points]`
This must be done by a GROUP_BY that will split the table into 2 separate sub-table, one for `source1` and the other for `source2`
The problem  is that the source name is a meta-data that must be referenced from outside of the table iterator; it can not be known before the parser has iterated over the data table.

MIVOT example:
```xml
<TABLE_MAPPING>
  <GROUP_BY dmrole="ahoc:sources" ref="_source_name">
    <INSTANCE dmrole="adhoc:source" dmtype="adhoc:Source">
       <ATTRIBUTE rdmrole="adhoc:Source.name" dmtype="ivoa:string" ref="?????"/>       
       <COLLECTION rdmrole="adhoc:Source.points"/>
         <TABLE_ROW_TEMPLATE>
                <INSTANCE dmrole="adhoc:Source.points" dmtype="adhoc:Point">
                    <ATTRIBUTE rdmrole="adhoc:Point.time" dmtype="ivoa:real" ref="_time"/>                           
                    <ATTRIBUTE rdmrole="adhoc:Point.mag" dmtype="ivoa:real" ref="_mag"/>    
               </INSTANCE>
         </TABLE_ROW_TEMPLATE>
       </COLLECTION>
    </INSTANCE>
  </GROUP_BY>
</TABLE_MAPPING>   
```

**Comment by mcdittmar** [comment]
This touches more on the GROUPBY node itself, rather than the issue of referencing Instances based on column (KEY) values, which is the focus of #6.

The GROUPBY basically defines 2 iterations:
1) over the unique KEY tuples
2) over the TABLE records

The thing here is that you'd like to generate some instances within each iteration level.
1) create 1 "adhoc:Source" instance for each unique "_source_name" in the table (the KEY tuple)
    1) NOTE: These instances can only differ by the KEY tuple values.  The rest of the content MUST be entirely literal or param derived.  
2) on each Source, attach a collection of "adhoc:Source.points" from the iteration over the Table records, filtering on the KEY tuple.

Suggestion: Since this case exists (the GAIA multi band case), this discussion would go more smoothly if we work that specific case annotated to the same models.  My implementation annotates it to Mango and SparseCube with 2 KEYs (_srcid, _band).  The MIIVOT implementation uses Mango and a 'mock_ts' model, annotating individual instances applying the FILTER  node with just the _band KEY.  This makes it a bit difficult to compare, but it looks like the first goal would be to replace the multiple Collections with a single GROUPBY.

PS: the node in the document and example is "GROUPBY" not "GROUP_BY".

**Comment by mcdittmar** [comment]
Some thoughts on this..
The crux of the issue here is that for GROUPBY to work, it must define sub-elements which have IDs and can be referenced in the INSTANCE content like a table FIELD/PARAM are.   These elements would define the tuple values over which GROUPBY is iterating... kind-of like virtual columns.

The block below is from the GAIA multi band case, generating 1 TimeSeries per Source_id/Band pair.
I'm using the tag GROUPBYKEY here, these are the tuple elements being iterated over.

```xml
<VODML>
  <GLOBALS>
    ...
  </GLOBALS>

  <!-- set up iteration over unique KEY tuples                             -->
  <!--   - obviously, requires all KEYs to be in same TABLE                -->
  <GROUPBY tableref="Results">
    <!-- iterates over tuples of unique value sets from the GROUPBYKEYs -->
    <GROUPBYKEY ID="_gb_sourceid" ref="_srcid" \>
    <GROUPBYKEY ID="_gb_band" ref="_band" \>

    <!-- create 1 TimeSeries per unique Source ID and BAND -->
    <INSTANCE dmtype="cube:SparseCube">
      <ATTRIBUTE dmrole="cube:DataProduct.dataset">
        <REFERENCE tableref="_Datasets">
	  <!-- uses current iteration tuple '_srcid' value as foreign key in Dataset reference matching -->
	  <!-- {ref} is defined as reference to VOTABLE PARAM|FIELD, this usage is in that theme, but not a FIELD|PARAM -->
          <FOREIGNKEY ref="_gb_srcid"/>
        </REFERENCE>
      </ATTRIBUTE>
      <ATTRIBUTE dmrole="cube:SparseCube.data">
        <COLLECTION>
          <JOIN tableref="Results" dmref="_ts_data">
            <!-- {*keyref} is defined as reference to VOTABLE PARAM|FIELD, this usage is in that theme, but not a FIELD|PARAM -->
            <FILTER foreignkey="_srcid" primarykey="_gb_srcid" />
            <FILTER foreignkey="_band" primarykey="_gb_band"  />
          </JOIN>
        </COLLECTION>
      </ATTRIBUTE>
    </INSTANCE>
  </GROUPBY>

  <TEMPLATES tableref="Results">
    <INSTANCE dmtype="cube:NDPoint" ID="_ts_data">
       ...
    </INSTANCE>
  </TEMPLATES>
</VODML>
```

**Comment by lmichel** [comment]
Just to make sure: Do you propose to set GROUP_BY as a VODML child (out of GLOBALS or TEMPLATES)?

**Comment by lmichel** [comment]
This suppose a specific rule to resolve references : `ELEMENT@ref must be resolved against GROUPBYKEY first if ELEMENT is enclosed in a GROUPBY`. 
This could work, but there is a risk of collision between VOTable IDs (presumably unique) and  GROUPBYKEY IDs that are not part of the VOTable.

**Comment by mcdittmar** [comment]
> Just to make sure: Do you propose to set GROUP_BY as a VODML child (out of GLOBALS or TEMPLATES)?

GLOBALS: defines singleton instances
TEMPLATES: defines an iteration over TABLE rows
GROUPBY: defines an iteration over a value set derived from a TABLE.

So, it does seem to be at a similar level.


> This could work, but there is a risk of collision between VOTable IDs (presumably unique) and GROUPBYKEY IDs that are not part of the VOTable.

To be honest, I really am not liking this element.  It is difficult to explain, and tries to generate virtual data to be used in annotation.  I agree that this is opening up possible conflicts (though I assumed IDs would need to be unique throughout the document), and blurs the definition of the endpoint of ELEMENT@ref attributes.

Maybe we should drop this for V1.0.  See how things evolve, and how much need there is for such an element.?
There are 2 other alternatives:
   1) Annotate each instance separately.  Obviously, this would generate huge annotations some cases and is not optimal.
   2) I handled this by adding a TABLE element containing the primary key tuples, then annotated the "GROUPBY" content as a TEMPLATE pointing to that TABLE using the 'normal' annotation elements.  At the time, I thought this was rather odd, but am now thinking this is a very reasonable solution.

**Comment by lmichel** [comment]
> So, it does seem to be at a similar level.

Agree

> To be honest, I really am not liking this element. 

To be honest, Neither do I

The problem is that we must be able to set a model field (e.g. SOURCEID) located out of the  table iterator (JOIN) with a value that has been read by that table iterator. I'm afraid there is no straightforward way to do it without using some sort of variable. This operation will require a pre-processing in any case.
I spent some time at looking at some magic solution based on specific elements, but nothing came out either.

Considering that
- GROUPBY requires a complex annotation pattern
- GROUPBY requires a 2 passes processing 
- GROUPBY can be replaced with a sequence of filtered JOINs that can be setup by the annoter (operating the data grouping actually)   

I follow your proposal to postpone the requirement.

**Comment by mcdittmar** [comment]
Fantastic!  what's next?

**Comment by lmichel** [comment]
Next
- Have you seen the @Zarquan post #12? (fair point)
- You haven't reply on my proposal to extract FIELD elements #5, do you agree?
- You were reluctant to introduce shortcuts for mapping `ivo:Quantity`. No change here?

Apart of this, the last point is the _dmrole_ location.
You know my position, it hasn't changed I'm afraid:
- Working with the @lmichel pattern until someone is able to show it cannot work
