### ISSUE TITLE
Automatic annotation report

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#73]
At the ADASS BoF, the audience showed a real interest for services able to provide annotated responses.
This supposes to operate automatic annotation processes.
In this context, we must have a way to inform the client the something went wrong.

I propose to add an optional element just below `<dm-mapping:VODML>` with both free text and status:

```XML
<dm-mapping:VODML>
    <dm-mapping:REPORT status="KO">
         Cannot generate annotations on computed columns
    </dm-mapping:REPORT>   
    ....
```
where `@status` is in `[KO, OK]` in reference to the test suite.

This wouldn't break anything in the current proposal.

**Comment by mcdittmar** [comment]
I'm not sure I understand this request.
As I understand things, there is already a mechanism for services to report issues to clients, which includes an error response of some sort.

For this VODML block to be returned to the client, the service must be returning a 'result' (an annotated VOTable).
Is this an attempt to support a soft error?
e.g.: the service can produce the VOTable requested, but for some reason, was unable to annotate it as requested.  Rather than failing entirely, you want to return the VOTable results with some indication that the annotation failed?

This end of the workflow is outside my experience, so I can't say that I have an opinion that I would strongly push.  My feeling is that this is not necessary in the annotation:
  * If the user asked for annotated VOTable they are presumably expecting to use the annotation.  If that cannot be produced.. this is an error.
  * the user can subsequently (or second choice) request a straight VOTable if they can handle that.

Is there a writeup for the case?  How would the client use that REPORT?

**Comment by lmichel** [comment]
Let my try to explain the rationale:
- The mapping is designed to independent from the VOTable, thus it must be self-consistent, thus the status element (if needed) must be into the mapping block.
- Imagine a TAP service doing annotations of TAP responses on the fly. This feature is known by clients, e.g. through the registry. If the annotation process fails for some reason, the model-aware client has to get this and to react accordingly, at least by giving the reason to the user.
- It is an attempts to support a soft error possibly risen by an automated annotation process.

Let me to give a concrete TAP example:
This basic query:
```SQL
SELECT * FROM table
```
can be annotated by the server, but if the user run
```SQL
SELECT count(*) FROM table
```
The annotation becomes irrelevant but this is not obvious for the end-user. In this case, a message like
```XML
<REPORT status-"KO">
    The response cannot be annotated with MANGO because your are requesting computed columns
</REPORT>
```
would help.

**Comment by lmichel** [comment]
Political rationale:
This feature has been proposed at the ADASS BoF `TAP and the DM`, and this must be taken into account.

**Comment by mcdittmar** [comment]
That sounds about like what I thought..
Like I said, how clients/services talk to each other is outside of my experience, so I have no real opinion here.

I see the element is added (#74), so I would just say that this is a different class of element which has to do with the client/service communication and nothing to do with the annotated data itself.  So, I think the case should be detailed specifically in the use cases section of the document.

Mark

**Comment by lmichel** [comment]
Agree, 
- The on the fly annotation issue has been pushed down to the appendices, it must be also mentionned in the use-cases
- It can also be stated as a requirement: `the mapping MUST be able to inform the client that something went wrong`
