### ISSUE TITLE
Preventing to resolve REFERENCEs with multiple INSTANCEs

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#84]
Section 4.9 REFERENCE:

![Screenshot 2022-01-18 at 10 32 29](https://user-images.githubusercontent.com/11462648/149909874-f8bbf7ea-a760-493a-ad62-7ecf3f11b508.png)

This does not work. If the mapping of the referenced table (@tableref="_target1") contains multiple instances, which is allowed, the `<REFERENCE>` element should be replaced with a n-uple of `<INSTANCE>` : not possible.

I suggest to make  `@dmref` attribute mandatory in order to make sur we will get only one `<INSTANCE>` to resolve the reference.

Listing 12 should be replaced with 
```xml
<dm-mapping:REFERENCE dmrole="_role" tableref="_target1" dmref="_instance_ref"> 
     <dm-mapping:FOREIGN_KEY ref="_col1" />
</dm-mapping:REFERENCE>
```
If `@dmref="_instance_ref"` cannot be resolved in the scope of `@tableref="_target1"`, an error must be risen.

**Comment by mcdittmar** [comment]
Let me see if I understand the problem here.
Dynamic Reference: points into a COLLECTION or TABLE using KEYs to isolate the proper instance being referenced.

What I don't understand is the text "to be replaced with the INSTANCE of ".  These are reference elements, which simply point to INSTANCEs elsewhere.

In our cases, I think we've used this to isolate the singular instance which we want to reference.  And I think you are pointing out a problem if the KEY has multiple matches.

> I suggest to make @dmref attribute mandatory in order to make sur we will get only one <INSTANCE> to resolve the reference.

I don't understand this.. the dynamic reference is for use under TEMPLATES, and the whole point is that you don't know which instance is appropriate on each iteration of the template... so dmref does not apply.

I'm feeling like the document must be clear that the REFERENCE element must always resolve to a single INSTANCE (using multiple KEYS if necessary).  If, in application, a scan resolves to >1 instance, then it is up to the implementation to decide what to do there ( first, last, error, ... ).  This would indicate the data is under-annotated.

**Comment by lmichel** [comment]
I agree, 
I mis-interpreted PRIMARY_KEY. Its plays the  @dmid role but with a value changing for each row.
Thanks for the clarification
