### ISSUE TITLE
The UType limitations must be clarified

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#95]
in introduction.pdf
![Screenshot 2022-02-04 at 13 28 48](https://user-images.githubusercontent.com/11462648/152529165-498a4002-eb39-4403-b1ad-3dbe793c5d30.png)

**Comment by mcdittmar** [comment]
I feel like a lot of this was really well described in the Mapping document.
The following is not necessarily suggested text, but contributing to the discussion of what is being stated.

The first block is describing the limitations of the utype approach.. 
  o not intended to be parsable, so only identifies what the leaf FIELD/PARAM is, not its context.
  o not reusable, the same element used in different contexts/models have different utypes; which hinders interoperability
  o constrained to single-table serializations.  All model elements must be contained within the same VOTable TABLE.
  o does not support annotating the VOTable content to multiple models (as TimeSeries or Catalog/Source )

The second block doesn't mention that utypes are long, though they usually are.
  o "In VODML, the simple UType string identifying a model leaf, is replaced by identifiers for the model element and for the role it plays in the parent object. As a consequence..."

**Comment by Bonnarel** [comment]
I have been thinking since a long time to the differences between the utype approach and the VODML-mapping approach. I think the actual limitation of utypes is that they don't fully allow  to populate instances of the model with values extracted from the TABLEs. 
This because they are pointers FROM FIELDS/PARAMS towards the model structure and not the reverse.  SO if several instances of the same class are used in an instance youb cannot know which one is populating what, but the role can still be known.
There are two ways to build utypes. Oe is similar to vodml-id and gives you a local riole. The other one is getting up towards the root of a (hierarchical/fllatened) point of view on the model. In this case it is not local, it is a full role in the wider extent.
Example is coverage.location in characterization. Full role in characterzitaion is given by the old style utype SpectralAxis.coverage.location which is different from SpatialAxis.coverage.location. 
But if Axes would have two locations (which is not the case, but just to illustrate my idea) then utypes are unsifficaint to populate the two coverage instances locations.
So :
  > The first block is describing the limitations of the utype approach..
> o not intended to be parsable, so only identifies what the leaf FIELD/PARAM is, not its context.
Indeed if the full utype is stored somewhere with its description and associated to the model you actually have some context.
> o not reusable, the same element used in different contexts/models have different utypes; which hinders interoperability
Yes. but this not always a drawback if we want the full role we need to distinguish the contexts.
> o constrained to single-table serializations. All model elements must be contained within the same VOTable TABLE.
This is a consequence of the limittaion of the approach I described above : no similar instance distinction is possible
> o does not support annotating the VOTable content to multiple models (as TimeSeries or Catalog/Source )
Note sure it's impossible to give cobined roles. I have to think about it

**Comment by lmichel** [comment]
In the context of the mapping spec, we do not have to justify that much why we do not work with UTypes.
Anyone volunteers to merge both FB and MCD input?
